### ISSUE TITLE
Device in HASS disconnects after sometime

### ISSUE THREAD

**Issue by aescolastico** [jonnybergdahl/HomeAssistant_Growcube_Integration#6]
So the integration for some reason stops being able to communicate with my grow cube after a few hours of adding the device. I have to delete and readd to fix it everytime

![image](https://github.com/jonnybergdahl/HomeAssistant_Growcube_Integration/assets/30540257/1be4e8e3-a43c-4870-b4c5-372b038c1c71)

**Comment by jonnybergdahl** [comment]
The current version does not do reconnect, as I haven't found a trusted way to detect disconnects. 

You can try reloading the integration instead. 
![image](https://github.com/jonnybergdahl/HomeAssistant_Growcube_Integration/assets/128166901/1cfe8649-683a-46d6-abe7-1a4d6c3745b1)

**Comment by aescolastico** [comment]
reloading unfortunately doesnt solve the problem. only readding does.

**Comment by 51av0sh** [comment]
Same issue with mine. I have to remove and re-add the integration after a few hours. It also mixes up the reading between all 4 sensors.

**Comment by jonnybergdahl** [comment]
Can you activate logging and let me know what errors you see?

In Integrations, goto Growcube and click the > icon. Bottom left, clikc Enable debug logging. 
Log is viewed under System - Logs.

**Comment by mliebl73** [comment]
[home-assistant_growcube_2024-05-16T15-38-27.315Z.log](https://github.com/jonnybergdahl/HomeAssistant_Growcube_Integration/files/15337857/home-assistant_growcube_2024-05-16T15-38-27.315Z.log)

does this help? (did not check for errors, but I definitely get disconnects / unknown data)

thanks for that integration anyway :)

**Comment by jonnybergdahl** [comment]
I still haven't added a proper reconnect, but I have fixed some issues in the growcube-client that made my device unavailable when there was a problem with a sensor. 
Please update to 0.9.4.

**Comment by mliebl73** [comment]
hmmmm I only see the 0.9.2 release

**Comment by jonnybergdahl** [comment]
Yes, sorry about that. 0.9.4 introduced a showstopper bug, so I had to pull it.
It is published now though.

**Comment by jonnybergdahl** [comment]
This should be fixed now. I pulled the cable, and it did reconnect after I plugged the cable in.

**Comment by mliebl73** [comment]
works like a charm, thank you!
